name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  paths: 
    - "server/**"

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout server code only
        uses: actions/checkout@v4
        with:
          sparse-checkout: server
          sparse-checkout-cone-mode: true
          fetch-depth: 1

      - name: Set up docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push unacademy-server
        run: |
          docker build -f ./server/Dockerfile -t vishal811/unacademy-server:latest ./server
          docker push vishal811/unacademy-server:latest
